# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [7]:
# Importing Numpy Library
import numpy as np

# creating a array using numpy arange
ar = np.arange(2,51,3)

# printing array
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [16]:
# importing numpy 
import numpy as np

# creating a 2 empty list:
list_1 = []
list_2 = []

# getting values for lst_1 from user:
for i in range(5):
    my_input = int(input("Enter the value for list_1 :"))
    list_1.append(my_input)


# getting values for lst_2 from user:
for i in range(5):
    my_input = int(input("Enter the value for list_2 :"))
    list_2.append(my_input)


# conversion of List to Array

array_1 = np.array(list_1)
array_2 = np.array(list_2)

# concatenating 2 array:

array_concat = np.concatenate((array_1,array_2))

print("concatenation of arrays are :", array_concat)

# Sorting of array

print("Sorted array :", np.sort(array_concat))


Enter the value for list_1 :1
Enter the value for list_1 :4
Enter the value for list_1 :5
Enter the value for list_1 :7
Enter the value for list_1 :2
Enter the value for list_2 :10
Enter the value for list_2 :5
Enter the value for list_2 :3
Enter the value for list_2 :12 
Enter the value for list_2 :13
concatenation of arrays are : [ 1  4  5  7  2 10  5  3 12 13]
Sorted array : [ 1  2  3  4  5  5  7 10 12 13]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [15]:
# importing numpy
import numpy as np

# creating a 2d array
arr = np.array([[1, 4, 7], [3, 6, 9], [1, 4, 7], [3, 6, 9]])

# Printing array dimensions (axes)
print("Dimensions of an array is :", arr.ndim)

# Printing size of array
print("Size of an array is :", array_1.size)

Dimensions of an array is : 2
Size of an array is : 12


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [5]:
import numpy as np

arr = np.arange(int(input()))
print("Test 1D array (shape) :", arr.shape)

two_d_array_row = arr[np.newaxis]
print("Test` 2D array for row is :", two_d_array_row.shape)

two_d_array_col = arr[:, np.newaxis]
print("Test` 2D array for column is :", two_d_array_col.shape)

10
Test 1D array (shape) : (10,)
Test` 2D array for row is : (1, 10)
Test` 2D array for column is : (10, 1)


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [12]:
# importing numpy
import numpy as np

# creating a array with square values
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])

# stacking and printing the value
print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))
print("\nVertical Append :", np.vstack((arr_1, arr_2)))


Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]

Vertical Append : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Questions 6:
__How to get unique items and counts of unique items?__

unique method in numpy is used to get the unique values from the list and return count attribute of unique method return the count of unique value from the list.

In [13]:
# importing numpy
import numpy as np

# creating a array 
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)

# making a 
arr = np.asarray((unique, counts)).T

print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
